### ISSUE TITLE
NoSuchMethodError - io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize

### ISSUE THREAD

**Issue by robfig** [lightstep/lightstep-tracer-java#106]
I'm seeing NoSuchMethodErrors with the latest release:

```
Caused by: java.lang.NoSuchMethodError: io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize()I
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:274) ~[CrmApiServer_deploy.jar:?]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:239) ~[CrmApiServer_deploy.jar:?]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:69) ~[CrmApiServer_deploy.jar:?]
	at com.lightstep.tracer.shared.CollectorClient.connect(CollectorClient.java:89) ~[CrmApiServer_deploy.jar:?]
	at com.lightstep.tracer.shared.CollectorClient.<init>(CollectorClient.java:36) ~[CrmApiServer_deploy.jar:?]
	at com.lightstep.tracer.shared.AbstractTracer.initializeCollectorClient(AbstractTracer.java:356) ~[CrmApiServer_deploy.jar:?]
	at com.lightstep.tracer.shared.AbstractTracer.addSpan(AbstractTracer.java:485) ~[CrmApiServer_deploy.jar:?]
	at com.lightstep.tracer.shared.Span.finish(Span.java:43) ~[CrmApiServer_deploy.jar:?]
	at com.lightstep.tracer.shared.Span.finish(Span.java:36) ~[CrmApiServer_deploy.jar:?]
```

I'm not confident I know the root cause, but it sounds like gRPC 1.2.0 might just be a bad release. 
https://github.com/GoogleCloudPlatform/java-docs-samples/issues/579

I'm not too familiar with Maven, but it seems to be the case that the latest lightstep-java release specifies grpc 1.2.0, so I think that should be changed:
https://mvnrepository.com/artifact/com.lightstep.tracer/lightstep-tracer-jre/0.12.4

Do you foresee any issues if I upgrade to grpc 1.4.0?

Thanks,
Rob

**Comment by joeblubaugh** [comment]
@robfig this isn't necessarily an issue with 1.2.0 - it's not having synchronized GRPC versions in a few build files. This is being fixed in issue #107

**Comment by danielamiao** [comment]
@robfig The fix has been merged and published to version `0.12.5`, it should be synced to Maven Central in ~10 minutes. Please try it and let us know if that resolves your issue. Thanks!

**Comment by robfig** [comment]
Hm, it has not fixed our issue. Actually, it looks like this may be an issue with Bazel. It includes a different version of grpc's AbstractManagedChannelImplBuilder.class than the one we have, which lacks that method. Blast.

**Comment by carlosalberto** [comment]
Closing this issue as it's old and it's most likely fixed. Please re-open if that's not the case.
